### ISSUE TITLE
    AttributeError: 'VAE' object has no attribute 'clone'

### ISSUE THREAD

**Issue by fritol** [layerdiffusion/sd-forge-layerdiffusion#2]
using the sanity check apple settings 
when i run it i always get

```
extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py", line 130, in process_before_every_sampling
        vae = p.sd_model.forge_objects.vae.clone()
   AttributeError: 'VAE' object has no attribute 'clone'
```

and a regular image is created

**Comment by banjaminicc** [comment]
https://github.com/layerdiffusion/sd-forge-layerdiffusion/issues/1#issue-2163289755

**Comment by ali0une** [comment]
Working with latest sd-forge git pull right now.

`Version: f0.0.17v1.8.0rc-latest-269-gef35383b
Commit hash: ef35383b4a1189cbbaa3dea65bf77787385f62a9`

**Comment by fritol** [comment]
> Working with latest sd-forge git pull right now.
> 
> > Version: f0.0.17v1.8.0rc-latest-269-gef35383b
> > Commit hash: ef35383b4a1189cbbaa3dea65bf77787385f62a9

not working either on ef35383b4a1189cbbaa3dea65bf77787385f62a9

**Comment by fritol** [comment]
> Working with latest sd-forge git pull right now.
> 
> > Version: f0.0.17v1.8.0rc-latest-269-gef35383b
> > Commit hash: ef35383b4a1189cbbaa3dea65bf77787385f62a9

thx
it worked

**Comment by fritol** [comment]
ss
